

services:
  web:
    build: .
    image: sekolah_app_image
    container_name: sekolah_app
    restart: always
    ports:
      - "80:8000"  # Akses dari internet port 80, masuk ke container port 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sekolah_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bismillah123  
      POSTGRES_DB: rq
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: